services:
  gui:
    volumes:
      - ${NBS_COLLECTION_PACKAGES}:/home/xf07id1/collection_packages
      - ${BEAMLINE_PODS_DIR}:/home/xf07id1/.ipython/profile_collection
    working_dir: /home/xf07id1/.ipython/profile_collection
    environment:
      - IPYTHONDIR=/home/xf07id1/.ipython/
      - NBS_SIM_MODE=1
    command: pixi run gui
