[configuration]
baseline = []
has_slits = false
has_motorized_samples = false
has_motorized_eref = false
has_polarization = false

[detector_sets.default]
primary = ""
normalization = ""
reference = ""

[devices]

[settings]
startup_modules = ["nbs_bl.startup", "vppem.startup"]
beamline = ["sst2", "sst1"]

[settings.plans]


[settings.redis.md]
host = "info.sst.nsls2.bnl.gov"
prefix = "vppem-"

[settings.redis.info]
host = "info.sst.nsls2.bnl.gov"
prefix = "vppem-"
db = 7

[settings.logging]
enabled = true
method = "nslsii"

[settings.tiled_writer]
enabled = false
profile = "nsls2"
catalog_path = ["vppem", "raw"]
api_key_env = "TILED_BLUESKY_WRITING_API_KEY_VPPEM"
subscribe_method = "post_document"

[settings.zmq]
enabled = true
host = "localhost:5577"