[settings.redis.md]
__merge__ = "replace"
host = "redis"
prefix = "vppem"

[settings.redis.info]
__merge__ = "replace"
host = "redisInfo"
prefix = ""
port = 60737
db = 7

[settings.logging]
__merge__ = "replace"
enabled = true
method = "nslsii"

[settings.tiled_writer]
__merge__ = "replace"
enabled = true
profile = "nbs"
subscribe_method = "post_document"

[settings.kafka]
name = "nbs"