[settings]
startup_modules = ["nbs_bl.startup", "vppem.startup", "vppem.sim_startup"]

[settings.redis.md]
__merge__ = "replace"
host = "redis"
prefix = "vppem"

[settings.redis.info]
__merge__ = "replace"
host = "redisInfo"
prefix = ""
port = 60737
db = 7

[settings.logging]
__merge__ = "replace"
enabled = true
method = "nslsii"

[settings.tiled_writer]
__merge__ = "replace"
enabled = true
#profile = "nbs"
#subscribe_method = "post_document"
api_key_env = "TILED_SINGLE_USER_API_KEY"
uri = "http://tiled_server:8000"
subscribe_method = "tiled_writer"


[settings.kafka]
enabled = false
name = "nbs"

[settings.zmq]
hostname = "zmq_proxy2"
port = 5577
out_port = 5578
start_proxy = false