# Define your beamline-specific devices here

[enpostender]
_target = "sst_base.energy.EnergyTender"
_group = ["source", "blconf"]
prefix = "SR:C07-ID:G1A{SST2:1}"
#prefix = ""
name = "SST2 Energy"

[en]
_alias = "enpostender.flycontrol"
_group = "motors"
_role = "energy"

[mono]
_alias = "enpostender.mono"

[dcm]
_alias = "enpostender.mono"

[h]
_alias = "enpostender.harmonic"

[U42]
_alias = "enpostender.u42"
_group = "motors"


[sampleVoltage]
_target = "sst_base.devices.KeithleySMU"
_group = ["motors"]
prefix = "XF:07ID1-ES{K2636B:1}"
name = "sampleVoltage"

[rbd1]
_target = "sst_base.devices.RBDFactory"
_group = "detectors"
prefix = "XF:07ID1-ES{RBD9103:05}"
rescale = -1
name = "rbd1"

[rbd2]
_target = "sst_base.devices.RBDFactory"
_group = "detectors"
prefix = "XF:07ID1-ES{RBD9103:09}"
rescale = -1
name = "rbd2"

[rbd3]
_target = "sst_base.devices.RBDFactory"
_group = "detectors"
prefix = "XF:07ID1-ES{RBD9103:12}"
rescale = -1
name = "rbd3"

[ring_current]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_current"
prefix = "SR:OPS-BI{DCCT:1}I:Real-I"
name = "ring_current"

[beamon]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "XF:07ID6-OP{Mono:DCM1-Fb:PF2}Beam-Sts"
kind = "hinted"
name = "beam on"

[ring_status]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_status"
prefix = "SR-OPS{}Mode-Sts"
name = "NSLS-II Status"
string = true

[psh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:1}"
name = "SST-2 Branch Shutter"

[psh2]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:2}"
name = "Shutter 2"

[psh4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:4}"
name = "Shutter 4"

[psh5]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:5}"
name = "Shutter 5"

[FEsh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "FE"
openval = 0
closeval = 1
prefix = "XF:07ID-PPS{Sh:FE}"
name = "Front-End Shutter"


[gv10]
_target = "sst_base.shutters.EPS_Shutter"
_group = "gatevalves"
shutter_type = "GV"
openval = 1
closeval = 0
prefix = "XF:07IDB-VA:1{HAXPES-GV:1}"
name = "downstream GV"

[fs4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 1
closeval = 0
prefix = "XF:07IDB-VA:1{FS:4A}"
name = "FS 4"

